#Application name
spring.application.name=MovieMS

#Embedded server port
server.port=8081

#Database configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREE
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

#Hibernate - JPA properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


